import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const DB_PATH = path.join(__dirname, 'db.json');

export interface EmployeeHistoryEvent {
  date: string;
  type: 'CTC_REVISION' | 'STATUS_CHANGE' | 'JOINED' | 'OTHER';
  old_value?: string | number;
  new_value: string | number;
  notes?: string;
}

export type PositionStatus = 'A' | 'V' | 'OYJ' | 'RoR' | 'RP' | 'H' | 'F' | 'M' | 'C' | 'T';

export interface Position {
  id: string; // e.g., P001
  title: string; // e.g., Software Engineer
  department: string;
  business_unit: string;
  sub_function?: string;
  reporting_to_position_id: string | null;
  status: PositionStatus;
  merged_into_position_id?: string;
  budgeted_ctc?: number;
  is_budget_approved?: boolean;
}

export interface Employee {
  id: string;
  emp_id?: string;
  position_id?: string;
  full_name: string;
  company_name: string;
  business_unit: string;
  department: string;
  designation: string;
  role_tier: number;
  employment_status: string;
  email_official: string;
  ctc_annual: number;
  ctc_currency: string;
  budget_allocated: number;
  dashboard_access: string;
  reporting_to_id: string | null;
  photo_url: string;
  join_date?: string;
  notice_start_date?: string | null;
  replaced_employee_id?: string | null;
  past_organization?: string;
  total_experience?: string;
  education_qualification?: string;
  history?: EmployeeHistoryEvent[];
  sub_function?: string;
}

export interface User {
  id: string;
  username: string;
  password: string;
  full_name: string;
  role: string;
  employee_id: string | null;
  avatar?: string;
}

// ─── WELLNESS MODULE SCHEMAS ──────────────────────────────────────────

export interface Question {
  id: string;
  type: 'MCQ_SINGLE' | 'MCQ_MULTI' | 'PARAGRAPH' | 'RATING';
  text: string;
  options?: string[]; // For MCQs
}

export interface Questionnaire {
  id: string;
  title: string;
  description: string;
  type: 'APTITUDE' | 'FEEDBACK' | 'WELLNESS' | 'GENERAL';
  created_by: string; // HOD or Admin ID
  created_at: string;
  status: 'DRAFT' | 'ACTIVE' | 'CLOSED';
  questions: Question[];
}

export interface Assignment {
  id: string;
  questionnaire_id: string;
  employee_id: string;
  assigned_by: string;
  assigned_at: string;
  status: 'PENDING' | 'COMPLETED';
}

export interface Answer {
  question_id: string;
  selected_options?: string[];
  text_response?: string;
  rating?: number; // 1 to 5 stars, or 1 to 10 marks
}

export interface Response {
  id: string;
  assignment_id: string;
  questionnaire_id: string;
  employee_id: string;
  submitted_at: string;
  answers: Answer[];
  ai_suggestion?: string; // Generated by Llama 3.1
  ai_consolation?: string; // Generated by Llama 3.1
  admin_status: 'VALID' | 'NEEDS_CORRECTION';
}

export interface CounsellingMessage {
  id: string;
  sender_id: string; // employee_id or counsellor_id
  text: string;
  timestamp: string;
}

export interface CounsellingSession {
  id: string;
  employee_id: string;
  counsellor_id: string | null;
  topic: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'CLOSED';
  created_at: string;
  messages: CounsellingMessage[];
}

export interface DailyFeedback {
  id: string;
  employee_id: string;
  date: string;
  workload_rating: number; // 1 to 5 (e.g., 1=Very Light, 5=Overwhelming)
  office_environment_queries: string;
  suggestions: string;
}

export interface DesignationTarget {
  designation: string;
  budgeted_hc: number;
  budget_allocated: number;
}

export interface DeptTarget {
  department: string;
  business_unit?: string;
  budgeted_hc: number;
  budget_allocated: number;
  target_attrition: number;
  designations?: DesignationTarget[];
}

export interface HRTargets {
  target_hiring_velocity: number;
  target_attrition_rate: number;
  global_planned_headcount?: number;
  global_open_positions?: number;
  departments: DeptTarget[];
}

// ─── RECRUITMENT MODULE SCHEMAS ──────────────────────────────────────

export interface JobRequisition {
  id: string; // e.g., REQ-001
  position_title: string;
  position_code: string;
  department: string;
  business_unit: string;
  location: string;
  reporting_manager_id: string | null;
  position_type: 'New Position' | 'Replacement Position';
  budgeted_ctc: number;
  grade: string;
  employment_type: string;
  number_of_openings: number;
  required_experience: string;
  qualification: string;
  key_skills: string;
  job_description: string;
  hiring_justification: string;
  expected_joining_date: string;
  status: 'Pending HR' | 'Pending Finance' | 'Pending Final' | 'Approved' | 'Rejected';
  created_at: string;
  is_active_link: boolean;
  link_views: number;
  applications_received: number;
}

export type CandidateStatus = 'Applied' | 'Pre-Screening' | 'HR Review' | 'Interview Scheduling' | 'Interview Completed' | 'Selected' | 'Offer Approval' | 'Offer Released' | 'Offer Accepted' | 'Joining' | 'Employee Creation' | 'Rejected' | 'Hold' | 'Withdrawn';

export interface Candidate {
  id: string;
  requisition_id: string;
  first_name: string;
  last_name: string;
  email: string;
  mobile_number: string;
  location: string;
  
  current_company: string;
  current_designation: string;
  total_experience: string;
  relevant_experience: string;
  current_ctc: number;
  expected_ctc: number;
  notice_period: string;
  reason_for_change?: string;
  
  resume_url: string;
  payslips_url: string;
  increment_letter_url?: string;
  offer_letter_url?: string;
  relieving_letter_url?: string;
  education_certificates_url?: string;

  status: CandidateStatus;
  applied_at: string;
  
  // Pre-screening
  qualification_match?: number;
  experience_match?: number;
  industry_relevance?: number;
  technical_fit?: number;
  communication_skills?: number;
  salary_alignment?: number;
  notice_period_feasibility?: number;
  recruiter_recommendation?: 'Shortlist' | 'Reject' | 'Hold';
  recruiter_remarks?: string;

  hr_approval_status?: 'Pending' | 'Approved' | 'Rejected' | 'Hold';
}

export interface Interview {
  id: string;
  candidate_id: string;
  type: 'Online' | 'Face-to-Face';
  platform?: string;
  date: string;
  time: string;
  interview_panel: string[]; // employee IDs
  venue_or_link: string;
  notes: string;
  status: 'Scheduled' | 'Completed' | 'Cancelled';
  technical_score?: number;
  communication_score?: number;
  domain_knowledge_score?: number;
  problem_solving_score?: number;
  behavioural_score?: number;
  cultural_fit_score?: number;
  overall_recommendation?: 'Select' | 'Hold' | 'Reject';
  evaluation_remarks?: string;
}

export interface Offer {
  id: string;
  candidate_id: string;
  position_id?: string;
  offered_ctc: number;
  grade: string;
  designation: string;
  joining_date: string;
  reporting_manager_id: string;
  status: 'Pending Recruiter' | 'Pending Budget Exception' | 'Pending HR Head' | 'Pending Dept Head' | 'Pending Final' | 'Offer Sent' | 'Offer Accepted' | 'Offer Declined' | 'Offer Expired' | 'Joined';
  created_at: string;
}

export interface BudgetException {
  id: string;
  offer_id: string;
  position_id: string;
  department: string;
  business_unit: string;
  budgeted_ctc: number;
  offered_ctc: number;
  variance_amount: number;
  status: 'Pending Dept Head' | 'Pending HR Head' | 'Pending Management' | 'Approved' | 'Rejected';
  created_at: string;
}

interface DB {
  users: User[];
  employees: Employee[];
  positions: Position[];
  appraisals: any[]; // Scaffolding for future feature
  templates: any[];  // Scaffolding for future feature
  candidates: Candidate[];
  job_requisitions: JobRequisition[];
  interviews: Interview[];
  offers: Offer[];
  budget_exceptions: BudgetException[];
  questionnaires: Questionnaire[];
  assignments: Assignment[];
  responses: Response[];
  counselling_sessions: CounsellingSession[];
  daily_feedbacks: DailyFeedback[];
  hr_targets: HRTargets;
}

const syncUsersWithEmployees = (db: DB): DB => {
  const newUsers: User[] = [];
  
  db.employees.forEach(emp => {
    let username = 'user';
    if (emp.email_official && emp.email_official.includes('@')) {
      username = emp.email_official.split('@')[0].toLowerCase().replace(/[^a-z0-9]/g, '');
    } else {
      username = emp.full_name.toLowerCase().replace(/[^a-z0-9]/g, '');
    }
    if (!username) username = 'user';

    let uniqueUsername = username;
    let counter = 1;
    while (newUsers.some(u => u.username === uniqueUsername)) {
      uniqueUsername = `${username}${counter}`;
      counter++;
    }

    newUsers.push({
      id: `u_${emp.id}`,
      username: uniqueUsername,
      password: 'password123',
      full_name: emp.full_name,
      role: emp.dashboard_access,
      employee_id: emp.id,
      avatar: emp.photo_url
    });
  });

  // Preserve non-employee users
  const nonEmployeeUsers = (db.users || []).filter(u => !u.employee_id);
  db.users = [...nonEmployeeUsers, ...newUsers];
  return db;
};

const syncPositionsWithEmployees = (db: DB): DB => {
  if (!db.positions) db.positions = [];
  const existingPosIds = new Set(db.positions.map(p => p.id));
  
  db.employees.forEach(emp => {
    let posStatus: PositionStatus = 'A';
    if (emp.employment_status === 'Resigned on Roll' || emp.employment_status === 'Under Notice Period') posStatus = 'RoR';
    else if (emp.employment_status === 'Replacement Joined') posStatus = 'RP';
    else if (emp.employment_status === 'Offered Yet to Join') posStatus = 'OYJ';
    else if (emp.employment_status === 'Inactive') posStatus = 'V';
    
    if (!emp.position_id || !existingPosIds.has(emp.position_id)) {
      const posId = emp.position_id || `P_${crypto.randomUUID().substring(0, 8)}`;
      emp.position_id = posId;
      
      let reporting_to_position_id: string | null = null;
      if (emp.reporting_to_id) {
        const mgr = db.employees.find(e => e.id === emp.reporting_to_id);
        if (mgr) {
          if (!mgr.position_id) {
            mgr.position_id = `P_${crypto.randomUUID().substring(0, 8)}`;
          }
          reporting_to_position_id = mgr.position_id;
        }
      }
      
      db.positions.push({
        id: posId,
        title: emp.designation || 'Unknown Role',
        department: emp.department || '',
        business_unit: emp.business_unit || '',
        sub_function: emp.sub_function || '',
        reporting_to_position_id,
        status: posStatus,
        budgeted_ctc: 0
      });
      existingPosIds.add(posId);
    } else {
      const pos = db.positions.find(p => p.id === emp.position_id);
      if (pos) {
        pos.status = posStatus;
        pos.title = emp.designation || pos.title;
        pos.department = emp.department || pos.department;
        pos.business_unit = emp.business_unit || pos.business_unit;
        pos.sub_function = emp.sub_function || pos.sub_function;
        
        if (emp.reporting_to_id) {
          const mgr = db.employees.find(e => e.id === emp.reporting_to_id);
          if (mgr && mgr.position_id) {
            pos.reporting_to_position_id = mgr.position_id;
          }
        } else {
          pos.reporting_to_position_id = null;
        }
      }
    }
  });

  return db;
};

let cachedDb: DB | null = null;

const readDb = (): DB => {
  if (cachedDb) return cachedDb;

  if (!fs.existsSync(DB_PATH)) {
    const seedPath = path.join(__dirname, 'db_seed.json');
    if (fs.existsSync(seedPath)) {
      fs.copyFileSync(seedPath, DB_PATH);
    } else {
      const defaultDb: DB = {
        users: [],
        employees: [],
        positions: [],
        appraisals: [],
        templates: [],
        candidates: [],
        job_requisitions: [],
        interviews: [],
        offers: [],
        budget_exceptions: [],
        questionnaires: [],
        assignments: [],
        responses: [],
        counselling_sessions: [],
        daily_feedbacks: [],
        hr_targets: {
          target_hiring_velocity: 4,
          target_attrition_rate: 8.5,
          departments: []
        }
      };
      fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
      fs.writeFileSync(DB_PATH, JSON.stringify(defaultDb, null, 2), 'utf-8');
    }
  }

  const data = fs.readFileSync(DB_PATH, 'utf-8');
  const parsed = JSON.parse(data.replace(/^\uFEFF/, ''));
  if (!parsed.users) parsed.users = [];
  if (!parsed.employees) parsed.employees = [];
  if (!parsed.positions) parsed.positions = [];
  if (!parsed.appraisals) parsed.appraisals = [];
  if (!parsed.templates) parsed.templates = [];
  if (!parsed.candidates) parsed.candidates = [];
  if (!parsed.job_requisitions) parsed.job_requisitions = [];
  if (!parsed.interviews) parsed.interviews = [];
  if (!parsed.offers) parsed.offers = [];
  if (!parsed.budget_exceptions) parsed.budget_exceptions = [];
  if (!parsed.questionnaires) parsed.questionnaires = [];
  if (!parsed.assignments) parsed.assignments = [];
  if (!parsed.responses) parsed.responses = [];
  if (!parsed.counselling_sessions) parsed.counselling_sessions = [];
  if (!parsed.daily_feedbacks) parsed.daily_feedbacks = [];
  if (!parsed.hr_targets) parsed.hr_targets = {
    target_hiring_velocity: 4,
    target_attrition_rate: 8.5,
    departments: []
  };
  
  // Auto-sync positions and users
  let db: DB = parsed;
  db = syncPositionsWithEmployees(db);
  
  const employeeUserCount = db.users.filter(u => u.employee_id).length;
  if (employeeUserCount !== db.employees.length) {
    db = syncUsersWithEmployees(db);
    fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf-8');
  } else {
    // If syncPositionsWithEmployees added positions, make sure we save them
    fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf-8');
  }
  cachedDb = db;
  return db;
};

const writeDb = (db: DB): void => {
  let syncedDb = syncPositionsWithEmployees(db);
  syncedDb = syncUsersWithEmployees(syncedDb);
  cachedDb = syncedDb;
  fs.writeFileSync(DB_PATH, JSON.stringify(syncedDb, null, 2), 'utf-8');
};

// User operations
export const getUsers = (): User[] => readDb().users;
export const getUserByUsername = (username: string): User | undefined =>
  readDb().users.find(u => u.username.toLowerCase() === username.toLowerCase());

// Employee operations
export const getEmployees = (): Employee[] => {
  const db = readDb();
  let modified = false;
  const now = new Date().getTime();
  const ninetyDaysInMs = 90 * 24 * 60 * 60 * 1000;

  db.employees.forEach(emp => {
    if (emp.employment_status === 'Resigned on Roll' && emp.notice_start_date) {
      if (now - new Date(emp.notice_start_date).getTime() >= ninetyDaysInMs) {
        emp.employment_status = 'Inactive';
        emp.notice_start_date = null;
        if (!emp.history) emp.history = [];
        emp.history.push({
          date: new Date().toISOString(),
          type: 'STATUS_CHANGE',
          old_value: 'Resigned on Roll',
          new_value: 'Inactive',
          notes: 'Notice period of 90 days completed automatically.'
        });
        modified = true;
      }
    }
  });

  if (modified) {
    writeDb(db);
  }

  return db.employees;
};
export const getPositions = (): Position[] => readDb().positions || [];

export const getEmployeeById = (id: string): Employee | undefined =>
  readDb().employees.find(e => e.id === id);

export const addEmployee = (employee: Employee): Employee => {
  const db = readDb();
  if (!employee.history) employee.history = [];
  employee.history.push({
    date: new Date().toISOString(),
    type: 'JOINED',
    new_value: employee.employment_status,
    notes: `Joined as ${employee.designation}`
  });

  if (!employee.position_id) {
    const posId = `P_${crypto.randomUUID().substring(0, 8)}`;
    employee.position_id = posId;

    let reporting_to_position_id: string | null = null;
    if (employee.reporting_to_id) {
      const mgr = db.employees.find(e => e.id === employee.reporting_to_id);
      if (mgr && mgr.position_id) {
        reporting_to_position_id = mgr.position_id;
      }
    }

    let posStatus: PositionStatus = 'A';
    if (employee.employment_status === 'Resigned on Roll') posStatus = 'RoR';
    else if (employee.employment_status === 'Replacement Joined') posStatus = 'RP';
    else if (employee.employment_status === 'Offered Yet to Join') posStatus = 'OYJ';
    else if (employee.employment_status === 'Inactive') posStatus = 'V';
    else if (employee.employment_status === 'Under Notice Period') posStatus = 'RoR';

    if (!db.positions) db.positions = [];
    db.positions.push({
      id: posId,
      title: employee.designation || 'Unknown Role',
      department: employee.department || '',
      business_unit: employee.business_unit || '',
      sub_function: employee.sub_function || '',
      reporting_to_position_id,
      status: posStatus,
      budgeted_ctc: 0
    });
  }

  db.employees.push(employee);

  if (employee.replaced_employee_id) {
    db.employees.forEach(e => {
      if (e.reporting_to_id === employee.replaced_employee_id) {
        e.reporting_to_id = employee.id;
      }
    });
  }

  writeDb(db);
  return employee;
};

export const bulkAddEmployees = (employees: Employee[]): Employee[] => {
  const db = readDb();
  if (!db.positions) db.positions = [];

  // Pass 1: Add history and create position IDs
  employees.forEach(emp => {
    if (!emp.history) emp.history = [];
    emp.history.push({
      date: new Date().toISOString(),
      type: 'JOINED',
      new_value: emp.employment_status,
      notes: `Bulk imported as ${emp.designation}`
    });

    if (!emp.position_id) {
      emp.position_id = `P_${crypto.randomUUID().substring(0, 8)}`;
    }
  });

  // Pass 2: Create Position entities and map manager position linkages
  const empIdToPosId = new Map<string, string>();
  db.employees.forEach(e => {
    if (e.position_id) empIdToPosId.set(e.id, e.position_id);
  });
  employees.forEach(e => {
    if (e.position_id) empIdToPosId.set(e.id, e.position_id);
  });

  employees.forEach(emp => {
    let reporting_to_position_id: string | null = null;
    if (emp.reporting_to_id && empIdToPosId.has(emp.reporting_to_id)) {
      reporting_to_position_id = empIdToPosId.get(emp.reporting_to_id)!;
    }

    let posStatus: PositionStatus = 'A';
    if (emp.employment_status === 'Resigned on Roll') posStatus = 'RoR';
    else if (emp.employment_status === 'Replacement Joined') posStatus = 'RP';
    else if (emp.employment_status === 'Offered Yet to Join') posStatus = 'OYJ';
    else if (emp.employment_status === 'Inactive') posStatus = 'V';
    else if (emp.employment_status === 'Under Notice Period') posStatus = 'RoR';

    const exists = db.positions.some(p => p.id === emp.position_id);
    if (!exists) {
      db.positions.push({
        id: emp.position_id!,
        title: emp.designation || 'Unknown Role',
        department: emp.department || '',
        business_unit: emp.business_unit || '',
        sub_function: emp.sub_function || '',
        reporting_to_position_id,
        status: posStatus,
        budgeted_ctc: emp.budget_allocated || emp.ctc_annual || 0
      });
    }
  });

  db.employees.push(...employees);
  writeDb(db);
  return employees;
};

export const updateEmployee = (id: string, data: Partial<Employee>): Employee | null => {
  const db = readDb();
  const idx = db.employees.findIndex(e => e.id === id);
  if (idx === -1) return null;
  
  const existing = db.employees[idx];
  const history = existing.history || [];

  // Track CTC revision
  if (data.ctc_annual !== undefined && data.ctc_annual !== existing.ctc_annual) {
    history.push({
      date: new Date().toISOString(),
      type: 'CTC_REVISION',
      old_value: existing.ctc_annual,
      new_value: data.ctc_annual
    });
  }

  // Track Status changes
  if (data.employment_status !== undefined && data.employment_status !== existing.employment_status) {
    history.push({
      date: new Date().toISOString(),
      type: 'STATUS_CHANGE',
      old_value: existing.employment_status,
      new_value: data.employment_status
    });

    if (data.employment_status === 'Resigned on Roll' && !data.notice_start_date && !existing.notice_start_date) {
      data.notice_start_date = new Date().toISOString();
    }

    // Update the position's status as well
    if (existing.position_id) {
      if (!db.positions) db.positions = [];
      const posIdx = db.positions.findIndex(p => p.id === existing.position_id);
      if (posIdx !== -1) {
        let posStatus: import('./database').PositionStatus = 'A';
        if (data.employment_status === 'Resigned on Roll') posStatus = 'RoR';
        else if (data.employment_status === 'Replacement Joined') posStatus = 'RP';
        else if (data.employment_status === 'Offered Yet to Join') posStatus = 'OYJ';
        else if (data.employment_status === 'Inactive') posStatus = 'V';
        else if (data.employment_status === 'Under Notice Period') posStatus = 'RoR';
        else if (data.employment_status === 'Active') posStatus = 'A';
        db.positions[posIdx].status = posStatus;
      }
    }
  }

  db.employees[idx] = { ...existing, ...data, history };

  if (data.replaced_employee_id) {
    db.employees.forEach(e => {
      if (e.reporting_to_id === data.replaced_employee_id) {
        e.reporting_to_id = id;
      }
    });
  }

  writeDb(db);
  return db.employees[idx];
};


export const deleteEmployee = (id: string) => {
  const db = readDb();
  const index = db.employees.findIndex(e => e.id === id);
  if (index !== -1) {
    const deleted = db.employees.splice(index, 1)[0];
    
    // Clean up empty positions
    if (db.positions) {
      const occupiedPositionIds = new Set(db.employees.map(e => e.position_id));
      db.positions = db.positions.filter(p => occupiedPositionIds.has(p.id));
    }

    writeDb(db);
    return deleted;
  }
  return null;
};

export const bulkDeleteEmployees = (ids: string[]): void => {
  const db = readDb();
  db.employees = db.employees.filter(e => !ids.includes(e.id));
  
  // Clean up empty positions
  if (db.positions) {
    const occupiedPositionIds = new Set(db.employees.map(e => e.position_id));
    db.positions = db.positions.filter(p => occupiedPositionIds.has(p.id));
  }
  
  writeDb(db);
};

export const savePositions = (positions: Position[]) => {
  const db = readDb();
  db.positions = positions;
  writeDb(db);
};

export const addPosition = (position: Position) => {
  const db = readDb();
  if (!db.positions) db.positions = [];
  db.positions.push(position);
  writeDb(db);
  return position;
};

export const updatePosition = (id: string, updates: Partial<Position>) => {
  const db = readDb();
  if (!db.positions) db.positions = [];
  const index = db.positions.findIndex(p => p.id === id);
  if (index !== -1) {
    db.positions[index] = { ...db.positions[index], ...updates };
    writeDb(db);
    return db.positions[index];
  }
  return null;
};// ─── WELLNESS OPERATIONS ──────────────────────────────────────────────

export const getQuestionnaires = (): Questionnaire[] => readDb().questionnaires;
export const addQuestionnaire = (q: Questionnaire): Questionnaire => {
  const db = readDb();
  db.questionnaires.push(q);
  writeDb(db);
  return q;
};

export const getAssignments = (empId?: string): Assignment[] => {
  const db = readDb();
  if (empId) return db.assignments.filter(a => a.employee_id === empId);
  return db.assignments;
};

export const addAssignment = (a: Assignment): Assignment => {
  const db = readDb();
  db.assignments.push(a);
  writeDb(db);
  return a;
};

export const updateAssignmentStatus = (id: string, status: 'PENDING' | 'COMPLETED') => {
  const db = readDb();
  const idx = db.assignments.findIndex(a => a.id === id);
  if (idx > -1) {
    db.assignments[idx].status = status;
    writeDb(db);
  }
};

export const getResponses = (): Response[] => readDb().responses;
export const addResponse = (r: Response): Response => {
  const db = readDb();
  db.responses.push(r);
  writeDb(db);
  return r;
};

export const getCounsellingSessions = (empId?: string): CounsellingSession[] => {
  const db = readDb();
  if (empId) return db.counselling_sessions.filter(s => s.employee_id === empId);
  return db.counselling_sessions;
};

export const addCounsellingSession = (s: CounsellingSession): CounsellingSession => {
  const db = readDb();
  db.counselling_sessions.push(s);
  writeDb(db);
  return s;
};

export const addCounsellingMessage = (sessionId: string, msg: CounsellingMessage) => {
  const db = readDb();
  const idx = db.counselling_sessions.findIndex(s => s.id === sessionId);
  if (idx > -1) {
    db.counselling_sessions[idx].messages.push(msg);
    writeDb(db);
  }
};

export const getDailyFeedbacks = (): DailyFeedback[] => readDb().daily_feedbacks;

export const addDailyFeedback = (f: DailyFeedback): DailyFeedback => {
  const db = readDb();
  db.daily_feedbacks.push(f);
  writeDb(db);
  return f;
};

// ─── TARGETS OPERATIONS ──────────────────────────────────────────────────
export const getHRTargets = (): HRTargets => readDb().hr_targets;
export const updateHRTargets = (targets: HRTargets): HRTargets => {
  const db = readDb();
  db.hr_targets = targets;

  // Sync vacant positions with targets
  if (!db.positions) db.positions = [];
  
  // Clean up all V positions
  db.positions = db.positions.filter(p => p.status !== 'V');
  
  // Re-generate V positions to meet targets
  targets.departments.forEach(dept => {
    const bu = dept.business_unit || '';
    if (dept.designations && dept.designations.length > 0) {
      dept.designations.forEach(desig => {
        const hc = Number(desig.budgeted_hc) || 0;
        const totalBudget = Number(desig.budget_allocated) || 0;
        const avgBudget = hc > 0 ? Math.round(totalBudget / hc) : 0;
        
        const activeCount = db.positions.filter(p => p.status !== 'V' && p.department === dept.department && (p.business_unit || '') === bu && p.title === desig.designation).length;
        const vacantNeeded = Math.max(0, hc - activeCount);
        
        for (let i = 0; i < vacantNeeded; i++) {
          db.positions.push({
            id: `P_${crypto.randomUUID().substring(0, 8)}`,
            title: desig.designation,
            department: dept.department,
            business_unit: bu,
            reporting_to_position_id: null,
            status: 'V', 
            budgeted_ctc: avgBudget,
            is_budget_approved: true
          });
        }
      });
    } else {
      const hc = Number(dept.budgeted_hc) || 0;
      const totalBudget = Number(dept.budget_allocated) || 0;
      const avgBudget = hc > 0 ? Math.round(totalBudget / hc) : 0;
      
      const activeCount = db.positions.filter(p => p.status !== 'V' && p.department === dept.department && (p.business_unit || '') === bu).length;
      const vacantNeeded = Math.max(0, hc - activeCount);
      
      for (let i = 0; i < vacantNeeded; i++) {
        db.positions.push({
          id: `P_${crypto.randomUUID().substring(0, 8)}`,
          title: "Unspecified Role",
          department: dept.department,
          business_unit: bu,
          reporting_to_position_id: null,
          status: 'V',
          budgeted_ctc: avgBudget,
          is_budget_approved: true
        });
      }
    }
  });

  writeDb(db);
  return db.hr_targets;
};

// ─── RECRUITMENT OPERATIONS ──────────────────────────────────────────────

export const getJobRequisitions = (): JobRequisition[] => readDb().job_requisitions;
export const getJobRequisitionById = (id: string): JobRequisition | undefined => readDb().job_requisitions.find(r => r.id === id);

export const addJobRequisition = (req: JobRequisition): JobRequisition => {
  const db = readDb();
  db.job_requisitions.push(req);
  writeDb(db);
  return req;
};

export const updateJobRequisition = (id: string, updates: Partial<JobRequisition>): JobRequisition | null => {
  const db = readDb();
  const idx = db.job_requisitions.findIndex(r => r.id === id);
  if (idx > -1) {
    db.job_requisitions[idx] = { ...db.job_requisitions[idx], ...updates };
    writeDb(db);
    return db.job_requisitions[idx];
  }
  return null;
};

export const deleteJobRequisition = (id: string): JobRequisition | null => {
  const db = readDb();
  const idx = db.job_requisitions.findIndex(r => r.id === id);
  if (idx > -1) {
    const deleted = db.job_requisitions.splice(idx, 1)[0];
    writeDb(db);
    return deleted;
  }
  return null;
};

export const getCandidates = (): Candidate[] => readDb().candidates;
export const getCandidateById = (id: string): Candidate | undefined => readDb().candidates.find(c => c.id === id);

export const addCandidate = (cand: Candidate): Candidate => {
  const db = readDb();
  db.candidates.push(cand);
  writeDb(db);
  return cand;
};

export const updateCandidate = (id: string, updates: Partial<Candidate>): Candidate | null => {
  const db = readDb();
  const idx = db.candidates.findIndex(c => c.id === id);
  if (idx > -1) {
    db.candidates[idx] = { ...db.candidates[idx], ...updates };
    writeDb(db);
    return db.candidates[idx];
  }
  return null;
};

export const deleteCandidate = (id: string): Candidate | null => {
  const db = readDb();
  const idx = db.candidates.findIndex(c => c.id === id);
  if (idx > -1) {
    const deleted = db.candidates.splice(idx, 1)[0];
    writeDb(db);
    return deleted;
  }
  return null;
};

export const getInterviews = (): Interview[] => readDb().interviews;
export const getInterviewById = (id: string): Interview | undefined => readDb().interviews.find(i => i.id === id);

export const addInterview = (interview: Interview): Interview => {
  const db = readDb();
  db.interviews.push(interview);
  writeDb(db);
  return interview;
};

export const updateInterview = (id: string, updates: Partial<Interview>): Interview | null => {
  const db = readDb();
  const idx = db.interviews.findIndex(i => i.id === id);
  if (idx > -1) {
    db.interviews[idx] = { ...db.interviews[idx], ...updates };
    writeDb(db);
    return db.interviews[idx];
  }
  return null;
};

export const getOffers = (): Offer[] => readDb().offers;
export const getOfferById = (id: string): Offer | undefined => readDb().offers.find(o => o.id === id);

export const addOffer = (offer: Offer): Offer => {
  const db = readDb();
  db.offers.push(offer);
  writeDb(db);
  return offer;
};

export const updateOffer = (id: string, updates: Partial<Offer>): Offer | null => {
  const db = readDb();
  const idx = db.offers.findIndex(o => o.id === id);
  if (idx > -1) {
    db.offers[idx] = { ...db.offers[idx], ...updates };
    writeDb(db);
    return db.offers[idx];
  }
  return null;
};

export const getBudgetExceptions = (): BudgetException[] => readDb().budget_exceptions || [];
export const getBudgetExceptionById = (id: string): BudgetException | undefined => readDb().budget_exceptions.find(e => e.id === id);
export const addBudgetException = (exc: BudgetException): BudgetException => {
  const db = readDb();
  if (!db.budget_exceptions) db.budget_exceptions = [];
  db.budget_exceptions.push(exc);
  writeDb(db);
  return exc;
};
export const updateBudgetException = (id: string, updates: Partial<BudgetException>) => {
  const db = readDb();
  if (!db.budget_exceptions) db.budget_exceptions = [];
  const index = db.budget_exceptions.findIndex(e => e.id === id);
  if (index !== -1) {
    db.budget_exceptions[index] = { ...db.budget_exceptions[index], ...updates };
    writeDb(db);
    return db.budget_exceptions[index];
  }
  return null;
};


export const resetDatabaseData = (): void => {
  const seedPath = path.join(__dirname, 'db_seed.json');
  if (fs.existsSync(seedPath)) {
    const data = fs.readFileSync(seedPath, 'utf-8');
    fs.writeFileSync(DB_PATH, data, 'utf-8');
  }
};

