import fs from 'fs';
import path from 'path';

const DB_PATH = path.join(__dirname, 'db.json');

export interface EmployeeHistoryEvent {
  date: string;
  type: 'CTC_REVISION' | 'STATUS_CHANGE' | 'JOINED' | 'OTHER';
  old_value?: string | number;
  new_value: string | number;
  notes?: string;
}

export interface Employee {
  id: string;
  emp_id?: string;
  full_name: string;
  company_name: string;
  business_unit: string;
  department: string;
  designation: string;
  role_tier: number;
  employment_status: string;
  email_official: string;
  ctc_annual: number;
  ctc_currency: string;
  budget_allocated: number;
  dashboard_access: string;
  reporting_to_id: string | null;
  photo_url: string;
  join_date?: string;
  notice_start_date?: string | null;
  replaced_employee_id?: string | null;
  past_organization?: string;
  total_experience?: string;
  education_qualification?: string;
  history?: EmployeeHistoryEvent[];
  sub_function?: string;
}

export interface User {
  id: string;
  username: string;
  password: string;
  full_name: string;
  role: string;
  employee_id: string | null;
  avatar?: string;
}

// ─── WELLNESS MODULE SCHEMAS ──────────────────────────────────────────

export interface Question {
  id: string;
  type: 'MCQ_SINGLE' | 'MCQ_MULTI' | 'PARAGRAPH' | 'RATING';
  text: string;
  options?: string[]; // For MCQs
}

export interface Questionnaire {
  id: string;
  title: string;
  description: string;
  type: 'APTITUDE' | 'FEEDBACK' | 'WELLNESS' | 'GENERAL';
  created_by: string; // HOD or Admin ID
  created_at: string;
  status: 'DRAFT' | 'ACTIVE' | 'CLOSED';
  questions: Question[];
}

export interface Assignment {
  id: string;
  questionnaire_id: string;
  employee_id: string;
  assigned_by: string;
  assigned_at: string;
  status: 'PENDING' | 'COMPLETED';
}

export interface Answer {
  question_id: string;
  selected_options?: string[];
  text_response?: string;
  rating?: number; // 1 to 5 stars, or 1 to 10 marks
}

export interface Response {
  id: string;
  assignment_id: string;
  questionnaire_id: string;
  employee_id: string;
  submitted_at: string;
  answers: Answer[];
  ai_suggestion?: string; // Generated by Llama 3.1
  ai_consolation?: string; // Generated by Llama 3.1
  admin_status: 'VALID' | 'NEEDS_CORRECTION';
}

export interface CounsellingMessage {
  id: string;
  sender_id: string; // employee_id or counsellor_id
  text: string;
  timestamp: string;
}

export interface CounsellingSession {
  id: string;
  employee_id: string;
  counsellor_id: string | null;
  topic: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'CLOSED';
  created_at: string;
  messages: CounsellingMessage[];
}

export interface DailyFeedback {
  id: string;
  employee_id: string;
  date: string;
  workload_rating: number; // 1 to 5 (e.g., 1=Very Light, 5=Overwhelming)
  office_environment_queries: string;
  suggestions: string;
}

export interface DesignationTarget {
  designation: string;
  budgeted_hc: number;
  budget_allocated: number;
}

export interface DeptTarget {
  department: string;
  budgeted_hc: number;
  budget_allocated: number;
  target_attrition: number;
  designations?: DesignationTarget[];
}

export interface HRTargets {
  target_hiring_velocity: number;
  target_attrition_rate: number;
  global_planned_headcount?: number;
  global_open_positions?: number;
  departments: DeptTarget[];
}

interface DB {
  users: User[];
  employees: Employee[];
  appraisals: any[]; // Scaffolding for future feature
  templates: any[];  // Scaffolding for future feature
  candidates: any[]; // Scaffolding for future feature
  questionnaires: Questionnaire[];
  assignments: Assignment[];
  responses: Response[];
  counselling_sessions: CounsellingSession[];
  daily_feedbacks: DailyFeedback[];
  hr_targets: HRTargets;
}

const syncUsersWithEmployees = (db: DB): DB => {
  const newUsers: User[] = [];
  
  db.employees.forEach(emp => {
    let username = 'user';
    if (emp.email_official && emp.email_official.includes('@')) {
      username = emp.email_official.split('@')[0].toLowerCase().replace(/[^a-z0-9]/g, '');
    } else {
      username = emp.full_name.toLowerCase().replace(/[^a-z0-9]/g, '');
    }
    if (!username) username = 'user';

    let uniqueUsername = username;
    let counter = 1;
    while (newUsers.some(u => u.username === uniqueUsername)) {
      uniqueUsername = `${username}${counter}`;
      counter++;
    }

    newUsers.push({
      id: `u_${emp.id}`,
      username: uniqueUsername,
      password: 'password123',
      full_name: emp.full_name,
      role: emp.dashboard_access,
      employee_id: emp.id,
      avatar: emp.photo_url
    });
  });

  // Preserve non-employee users
  const nonEmployeeUsers = (db.users || []).filter(u => !u.employee_id);
  db.users = [...nonEmployeeUsers, ...newUsers];
  return db;
};

const readDb = (): DB => {
  const data = fs.readFileSync(DB_PATH, 'utf-8');
  const parsed = JSON.parse(data.replace(/^\uFEFF/, ''));
  if (!parsed.users) parsed.users = [];
  if (!parsed.employees) parsed.employees = [];
  if (!parsed.appraisals) parsed.appraisals = [];
  if (!parsed.templates) parsed.templates = [];
  if (!parsed.candidates) parsed.candidates = [];
  if (!parsed.questionnaires) parsed.questionnaires = [];
  if (!parsed.assignments) parsed.assignments = [];
  if (!parsed.responses) parsed.responses = [];
  if (!parsed.counselling_sessions) parsed.counselling_sessions = [];
  if (!parsed.daily_feedbacks) parsed.daily_feedbacks = [];
  if (!parsed.hr_targets) parsed.hr_targets = {
    target_hiring_velocity: 4,
    target_attrition_rate: 8.5,
    departments: []
  };
  
  // Auto-sync users if count does not match or if we want to ensure freshness
  let db: DB = parsed;
  const employeeUserCount = db.users.filter(u => u.employee_id).length;
  if (employeeUserCount !== db.employees.length) {
    db = syncUsersWithEmployees(db);
    fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf-8');
  }
  return db;
};

const writeDb = (db: DB): void => {
  const syncedDb = syncUsersWithEmployees(db);
  fs.writeFileSync(DB_PATH, JSON.stringify(syncedDb, null, 2), 'utf-8');
};

// User operations
export const getUsers = (): User[] => readDb().users;
export const getUserByUsername = (username: string): User | undefined =>
  readDb().users.find(u => u.username.toLowerCase() === username.toLowerCase());

// Employee operations
export const getEmployees = (): Employee[] => readDb().employees;

export const getEmployeeById = (id: string): Employee | undefined =>
  readDb().employees.find(e => e.id === id);

export const addEmployee = (employee: Employee): Employee => {
  const db = readDb();
  if (!employee.history) employee.history = [];
  employee.history.push({
    date: new Date().toISOString(),
    type: 'JOINED',
    new_value: employee.employment_status,
    notes: `Joined as ${employee.designation}`
  });
  db.employees.push(employee);

  if (employee.replaced_employee_id) {
    db.employees.forEach(e => {
      if (e.reporting_to_id === employee.replaced_employee_id) {
        e.reporting_to_id = employee.id;
      }
    });
  }

  writeDb(db);
  return employee;
};

export const bulkAddEmployees = (employees: Employee[]): Employee[] => {
  const db = readDb();
  employees.forEach(emp => {
    if (!emp.history) emp.history = [];
    emp.history.push({
      date: new Date().toISOString(),
      type: 'JOINED',
      new_value: emp.employment_status,
      notes: `Bulk imported as ${emp.designation}`
    });
  });
  db.employees.push(...employees);
  writeDb(db);
  return employees;
};

export const updateEmployee = (id: string, data: Partial<Employee>): Employee | null => {
  const db = readDb();
  const idx = db.employees.findIndex(e => e.id === id);
  if (idx === -1) return null;
  
  const existing = db.employees[idx];
  const history = existing.history || [];

  // Track CTC revision
  if (data.ctc_annual !== undefined && data.ctc_annual !== existing.ctc_annual) {
    history.push({
      date: new Date().toISOString(),
      type: 'CTC_REVISION',
      old_value: existing.ctc_annual,
      new_value: data.ctc_annual
    });
  }

  // Track Status changes
  if (data.employment_status !== undefined && data.employment_status !== existing.employment_status) {
    history.push({
      date: new Date().toISOString(),
      type: 'STATUS_CHANGE',
      old_value: existing.employment_status,
      new_value: data.employment_status
    });
  }

  db.employees[idx] = { ...existing, ...data, history };

  if (data.replaced_employee_id) {
    db.employees.forEach(e => {
      if (e.reporting_to_id === data.replaced_employee_id) {
        e.reporting_to_id = id;
      }
    });
  }

  writeDb(db);
  return db.employees[idx];
};

export const deleteEmployee = (id: string): boolean => {
  const db = readDb();
  const idx = db.employees.findIndex(e => e.id === id);
  if (idx === -1) return false;
  db.employees.splice(idx, 1);
  writeDb(db);
  return true;
};

export const bulkDeleteEmployees = (ids: string[]): void => {
  const db = readDb();
  db.employees = db.employees.filter(e => !ids.includes(e.id));
  writeDb(db);
};


// ─── WELLNESS OPERATIONS ──────────────────────────────────────────────

export const getQuestionnaires = (): Questionnaire[] => readDb().questionnaires;
export const addQuestionnaire = (q: Questionnaire): Questionnaire => {
  const db = readDb();
  db.questionnaires.push(q);
  writeDb(db);
  return q;
};

export const getAssignments = (empId?: string): Assignment[] => {
  const db = readDb();
  if (empId) return db.assignments.filter(a => a.employee_id === empId);
  return db.assignments;
};

export const addAssignment = (a: Assignment): Assignment => {
  const db = readDb();
  db.assignments.push(a);
  writeDb(db);
  return a;
};

export const updateAssignmentStatus = (id: string, status: 'PENDING' | 'COMPLETED') => {
  const db = readDb();
  const idx = db.assignments.findIndex(a => a.id === id);
  if (idx > -1) {
    db.assignments[idx].status = status;
    writeDb(db);
  }
};

export const getResponses = (): Response[] => readDb().responses;
export const addResponse = (r: Response): Response => {
  const db = readDb();
  db.responses.push(r);
  writeDb(db);
  return r;
};

export const getCounsellingSessions = (empId?: string): CounsellingSession[] => {
  const db = readDb();
  if (empId) return db.counselling_sessions.filter(s => s.employee_id === empId);
  return db.counselling_sessions;
};

export const addCounsellingSession = (s: CounsellingSession): CounsellingSession => {
  const db = readDb();
  db.counselling_sessions.push(s);
  writeDb(db);
  return s;
};

export const addCounsellingMessage = (sessionId: string, msg: CounsellingMessage) => {
  const db = readDb();
  const idx = db.counselling_sessions.findIndex(s => s.id === sessionId);
  if (idx > -1) {
    db.counselling_sessions[idx].messages.push(msg);
    writeDb(db);
  }
};

export const getDailyFeedbacks = (): DailyFeedback[] => readDb().daily_feedbacks;

export const addDailyFeedback = (f: DailyFeedback): DailyFeedback => {
  const db = readDb();
  db.daily_feedbacks.push(f);
  writeDb(db);
  return f;
};

// ─── TARGETS OPERATIONS ──────────────────────────────────────────────────
export const getHRTargets = (): HRTargets => readDb().hr_targets;
export const updateHRTargets = (targets: HRTargets): HRTargets => {
  const db = readDb();
  db.hr_targets = targets;
  writeDb(db);
  return db.hr_targets;
};

export const resetDatabaseData = (): void => {
  const seedPath = path.join(__dirname, 'db_seed.json');
  if (fs.existsSync(seedPath)) {
    const data = fs.readFileSync(seedPath, 'utf-8');
    fs.writeFileSync(DB_PATH, data, 'utf-8');
  }
};
