import asyncio
from typing import AsyncGenerator
from aira.orchestrator.providers.interfaces import IAIProvider
from aira.shared.logger import get_aira_logger

logger = get_aira_logger("mock_ai_provider")

class MockAIProvider(IAIProvider):
    def __init__(self, simulate_latency: float = 0.5, simulate_failure: bool = False):
        self.simulate_latency = simulate_latency
        self.simulate_failure = simulate_failure
        self.name = "MockAIProvider"
        
    async def generate(self, prompt: str) -> str:
        logger.info(f"MockAIProvider: Generating response for prompt snippet: {prompt[:50]}...")
        await asyncio.sleep(self.simulate_latency)
        if self.simulate_failure:
            raise Exception("Simulated Transient Provider Failure")
        return "This is a strictly mock response generated by the MockAIProvider."
        
    async def stream(self, prompt: str) -> AsyncGenerator[str, None]:
        await asyncio.sleep(self.simulate_latency)
        words = ["This ", "is ", "a ", "mock ", "stream."]
        for w in words:
            yield w
            await asyncio.sleep(0.1)

    def token_count(self, text: str) -> int:
        return int(len(text.split()) * 1.3)
        
    def estimate_cost(self, tokens: int) -> float:
        return (tokens / 1000.0) * 0.002
        
    async def health(self) -> bool:
        return not self.simulate_failure

    def supports_tools(self) -> bool:
        return True
