name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      
    - name: Configure Kubernetes credentials
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_PROD }}
        
    - name: Helm Upgrade
      run: |
        helm upgrade --install aira-mcp ./backend-python/deployment/helm/aira-mcp \
          --namespace aira-prod \
          --create-namespace \
          -f ./backend-python/deployment/helm/aira-mcp/values-prod.yaml \
          --set image.tag=${{ github.event.release.tag_name }}
